config/routes.rb
JobTracker::Application.routes.draw do
  resources :companies

  resources :people

  root :to => 'companies#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :name, :website, :notes, :source

  validates_presence_of :name

end

app/models/person.rb
class Person < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	
	def index
		@companies = Company.all
	end

	def new
		@company = Company.new
	end

	def show
		@company = Company.find(params[:id])
	end

	def create
		@company = Company.new(params[:company])
		if @company.save
			redirect_to companies_path
		else
			redirect_to new_company_path
		end
	end

	def edit
		@company = Company.find(params[:id])
	end

	def update
		@company = Company.find(params[:id])
		@company.update_attributes(params[:company])
	end

	def destroy
		@company = Company.find(params[:id])
		@company.destroy
	end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => {:multipart => true} do |f| %>

<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>

<p><%=f.label :website %></p>
<p><%= f.text_field :website %></p>

<p><%= f.label :notes %></p>
<p><%= f.text_area :notes %></p>

<p><%= f.label :source %></p>
<p><%= f.text_field :source %></p>

<%= f.submit %>

<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company Information</h1>

<%= render 'form' %>

<%= link_to 'Home', companies_path %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<% @companies.each do |company| %>
<ul>
	<li><%= link_to company.name, company_path(company) %></li>
</ul>
<% end %>
<p><%= link_to 'New', new_company_path %></p>

app/views/companies/new.html.erb
<h1>Add a New Company</h1>

<%= render 'form' %>

<%= link_to 'Home', companies_path %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p><%= @company.website %></p>

<div>Notes:
<p><%= @company.notes %></p>
</div>

<p><%= @company.source %></p>

<p><%= link_to 'Home', companies_path %></p>
<p><%= link_to 'Edit', edit_company_path(@company) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>